################################################################
# Middlewares
# Dynamic configuration
################################################################

http:
  middlewares:
    gzip:
      compress: {}