################################################################
# Middlewares
# https://doc.traefik.io/traefik/middlewares/http/redirectscheme/
# Dynamic configuration
################################################################

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true