################################################################
# Middlewares
# Dynamic configuration
################################################################

http:
  middlewares:
    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers